tasks:
  - name: extra-stargate-tiktok
    before: |
      cd /workspace/extra-stargate-tiktok
      nvm install node
      npm install -g npm@latest
      npm install -g netlify-cli
      npm install
    command: |
      echo "extra-stargate-tiktok gitpod ready - LET'S DO THIS!"
      gp open README.md
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore    
